Minor changes and translation of new pages into Russian
tgsnake/docs pull request #22
Opened 2024-04-06 05:00 UTC by kiogia

2024-04-06 05:11 UTC, butthx requested changes

2024-04-06 05:11 UTC, butthx commented on pages/getting-started.ru.mdx
Hi, Thank you for helping to translate, but here I see a conflict. Maybe you can fix it before I merge.

2024-04-07 03:26 UTC, kiogia commented on pages/getting-started.ru.mdx
Corrected. Thanks for noticing!

2024-04-07 03:38 UTC, butthx approved these changes

2024-04-07 03:38 UTC, merged